# Generated by Django 5.1.2 on 2024-10-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watches',
            name='brand',
            field=models.CharField(default='Fosil', max_length=30),
            preserve_default=False,
        ),
    ]
