# Generated by Django 5.1.2 on 2024-10-28 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0002_watches_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='watches',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='watches',
            name='description',
            field=models.TextField(),
        ),
    ]
